In [1]:
import pandas as pd
import random
from faker import Faker

In [ ]:
faker = Faker('pt_BR')

dados_pessoais = []

for _ in range(100):
    dados_pessoais.append({
        'nome': faker.name(),
        'email': faker.email(),
        'cpf': faker.cpf(),
        'data_nascimento': faker.date_of_birth(minimum_age=18, maximum_age=60).strftime('%d, %m, %Y'),
        'idade': random.randint(18, 60),
        'endereco': faker.address(),
        'cidade': faker.city(),
        'estado': faker.state_abbr(),
        'telefone': faker.phone_number()
    })

df_pessoas = pd.DataFrame(dados_pessoais)

df_pessoas

df_pessoas.to_csv('pessoas.csv', index=False)

,nome,email,cpf,data_nascimento,idade,endereco,cidade,estado,telefone
0,Marina Pires,mfernandes@example.net,851.629.347-55,"16, 01, 1976",19,"Avenida Novaes, 3\nPousada Santo Antonio\n4216...",Barbosa da Praia,RS,+55 (031) 3723 1818
1,Maria Helena Nogueira,levi62@example.com,974.835.612-46,"20, 11, 1964",50,Passarela Henrique Nogueira\nOutro\n45739-539 ...,Pereira,SP,+55 61 0949-6659
2,Milena Mendes,ealbuquerque@example.com,523.784.190-23,"16, 06, 1990",53,"Vale de Lima, 871\nGuaratã\n32112893 Farias / PE",Mendes da Praia,BA,+55 11 1072 1385
3,Ryan Castro,gabriela28@example.org,357.482.961-28,"01, 07, 1970",20,"Recanto Costa, 4\nFloresta\n67223-573 da Cruz ...",Nascimento,CE,71 8636 7126
4,Vitor da Cruz,nataliacasa-grande@example.net,918.643.072-69,"29, 05, 1975",54,"Conjunto de Aragão, 71\nAlto Vera Cruz\n713123...",da Cunha de Lima,CE,81 6063 7793
...,...,...,...,...,...,...,...,...,...
95,Henry Sousa,zda-paz@example.net,524.619.307-16,"20, 12, 1999",25,"Trecho da Mata, 890\nTiradentes\n50833-056 Pin...",Nogueira,TO,0900-891-0076
96,Enzo Gabriel Vieira,duartetheodoro@example.org,462.591.073-07,"22, 10, 1968",54,"Chácara de Gomes, 887\nEstoril\n56004605 Silva...",da Costa do Sul,AL,11 6622-4486
97,Luiz Miguel Sousa,antonylima@example.org,037.498.261-96,"31, 08, 1976",28,Lago Cassiano\nBoa União 1ª Seção\n81296757 Pi...,Viana da Mata,RR,0300 596 9865
98,Henrique Fernandes,matheusnovais@example.com,536.917.280-30,"05, 05, 1981",49,Recanto Moura\nVila União\n23125409 Nunes de P...,Barros de Abreu,PA,0500-724-4145
99,Emanuel Campos,olivianovais@example.net,471.623.085-62,"03, 10, 1989",43,"Aeroporto Isabela Rios, 142\nEsperança\n16388-...",da Conceição,DF,+55 21 5923 9256